version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    exclude-paths:
      - "examples/**"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
