# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: "List tasks"
    cmds:
      - task --list
    silent: true

  install:
    desc: Install dependencies
    cmds:
      - uv sync
      - uv pip install -e .

  run:
    desc: "Run the dbt-mcp server"
    cmds:
      - ./.venv/bin/mcp run ./dbt_mcp/main.py

  dev:
    desc: "Run the dbt-mcp server in development mode"
    cmds:
      - ./.venv/bin/mcp dev ./dbt_mcp/main.py

  inspector:
    desc: "Run the dbt-mcp server with MCP inspector"
    cmds:
      - npx @modelcontextprotocol/inspector ./.venv/bin/mcp run dbt_mcp/main.py

  test:
    desc: "Run the tests"
    cmds:
      - uv run pytest tests

  test:integration:
    desc: "Run the integration tests"
    cmds:
      - uv run pytest tests/integration

  test:unit:
    desc: "Run the unit tests"
    cmds:
      - uv run pytest tests/unit
