query AppliedSemanticModelResources(
    $environmentId: BigInt!,
    $filter: AppliedResourcesFilter!,
    $after: String,
    $first: Int
) {
    environment(id: $environmentId) {
        applied {
            resources(filter: $filter, after: $after, first: $first) {
                pageInfo {
                    hasNextPage
                    endCursor
                }
                edges {
                    node {
                        __typename
                        ... on SemanticModelDefinitionNode {
                            uniqueId
                            name
                            description
                            defaults {
                                aggTimeDimension
                            }
                            entities {
                                name
                                type
                                description
                            }
                            dimensions {
                                name
                                type
                                description
                                typeParams {
                                    timeGranularity
                                }
                            }
                            measures {
                                name
                                expr
                                description
                                agg
                            }
                        }
                    }
                }
            }
        }
    }
}
