query SourceDetails(
  $environmentId: BigInt!
  $filter: AppliedResourcesFilter!
  $after: String
  $first: Int
) {
  environment(id: $environmentId) {
    applied {
      resources(filter: $filter, after: $after, first: $first) {
        pageInfo {
          hasNextPage
          endCursor
        }
        edges {
          node {
            ... on SourceAppliedStateNode {
              catalog {
                columns {
                  comment
                  description
                  index
                  meta
                  name
                  tags
                  type
                }
              }
              freshness {
                maxLoadedAt
                maxLoadedAtTimeAgoInS
                freshnessStatus
              }
              comment
              owner
              rowCountStat
              type
              uniqueId
              name
              identifier
              description
              sourceName
              database
              schema
            }
          }
        }
      }
    }
  }
}
