query AppliedSourceResources(
    $environmentId: BigInt!,
    $filter: AppliedResourcesFilter!,
    $after: String,
    $first: Int
) {
    environment(id: $environmentId) {
        applied {
            resources(filter: $filter, after: $after, first: $first) {
                pageInfo {
                    hasNextPage
                    endCursor
                }
                edges {
                    node {
                        __typename
                        ... on SourceAppliedStateNode {
                            resourceType
                            uniqueId
                            name
                            description
                            sourceName
                            identifier
                            database
                            schema
                            freshness {
                                maxLoadedAt
                                maxLoadedAtTimeAgoInS
                                freshnessStatus
                            }
                            catalog {
                                columns {
                                    name
                                    type
                                    description
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
