[project]
name = "openai-agent"
version = "0.1.0"
description = "A simple example of using this MCP server with OpenAI Agents"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["openai-agents>=0.1.0"]
