name: Setup Python
description: Setup Python for ai-codegen-api

runs:
  using: "composite"
  steps:
    - name: Setup python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Setup uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Install the project
      shell: bash
      run: uv sync
