name: Setup Python and pnpm
description: Setup Python, uv, and pnpm for dbt-mcp

runs:
  using: "composite"
  steps:
    - name: Setup python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Setup uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Setup pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
      with:
        version: 10

    - name: Install the project
      shell: bash
      run: uv sync
