name: CODEOWNERS Coverage Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  validate-codeowners:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: mszostok/codeowners-validator@7f3f5e28c6d7b8dfae5731e54ce2272ca384592f
        with:
          github_access_token: "${{ secrets.OWNERS_VALIDATOR_GITHUB_SECRET }}"
          checks: "duppatterns"
          experimental_checks: "notowned"
