name: Create release PR
permissions:
  contents: write
  pull-requests: write
on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: The version bump type.
        default: minor
        options:
          - major
          - minor
          - patch

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-python

      - name: Batch changes
        uses: miniscruff/changie-action@6dcc2533cac0495148ed4046c438487e4dceaa23
        with:
          version: latest
          args: batch ${{ inputs.bump }}

      - name: Merge
        uses: miniscruff/changie-action@6dcc2533cac0495148ed4046c438487e4dceaa23
        with:
          version: latest
          args: merge

      - name: Get the latest version
        id: changie-latest
        uses: miniscruff/changie-action@6dcc2533cac0495148ed4046c438487e4dceaa23
        with:
          version: latest
          args: latest

      - name: Set latest package version
        id: package-version
        run: |
          VERSION="${{ steps.changie-latest.outputs.output }}"
          VERSION_NO_V=$(echo "$VERSION" | cut -c 2-)

          MESSAGE=$(cat ".changes/$VERSION.md")

          {
          echo "version=$VERSION_NO_V"
          echo "message<<EOF"
          echo "$MESSAGE"
          echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
        with:
          title: "version: ${{ steps.package-version.outputs.version }}"
          branch: release/${{ steps.package-version.outputs.version }}
          commit-message: |
            version: ${{ steps.package-version.outputs.version }}

            ${{ steps.package-version.outputs.message }}
          body: |
            ## version: ${{ steps.package-version.outputs.version }}

            ${{ steps.package-version.outputs.message }}
