name: PR pipeline

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
  check:
    name: Run tests
    runs-on: ubuntu-24.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Setup uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install go-task
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
      - name: Install dependencies
        run: task install
      - name: Run tests
        run: task test:unit
