name: Publish dbt-mcp to PyPI
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: ./.github/actions/setup-python
        id: setup-python

      - name: Install go-task
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Run tests
        run: task test:unit

      - name: Build
        run: task build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
        with:
          packages-dir: ./dist

  create-github-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # required to create a release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for changie to work correctly

      - name: Get the latest version
        id: changie-latest
        uses: miniscruff/changie-action@6dcc2533cac0495148ed4046c438487e4dceaa23
        with:
          version: latest
          args: latest

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.changie-latest.outputs.version }}
        run: |
          echo "Creating release for version: $VERSION"
          gh release create "$VERSION" \
            --notes-file ".changes/$VERSION.md" \
            --title "$VERSION"
