name: Publish to PyPI
run-name: Publish to ${{ inputs.pypi-server == 'pypi' && 'production' || 'test' }} PyPI

on:
  workflow_dispatch:
    inputs:
      pypi-server:
        description: "The PyPI server to publish to"
        type: choice
        options:
          - pypi
          - test-pypi

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-24.04
    environment:
      name: ${{ inputs.pypi-server == 'pypi' && 'pypi' || 'pypiTest' }}
    permissions:
      # this permission is required for trusted publishing
      # see https://github.com/marketplace/actions/pypi-publish
      id-token: write
      contents: read
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup python
        uses: ./.github/actions/setup-python
        id: setup-python
      - name: Install go-task
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
      # TODO: Uncomment this when we have tests
      # - name: Run tests
      #   run: task test:unit
      - name: Build
        run: task build
      - name: Publish to test PyPI
        if: inputs.pypi-server == 'test-pypi'
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
        with:
          packages-dir: ./dist
          repository-url: https://test.pypi.org/legacy/
      - name: Publish to PyPI
        if: inputs.pypi-server == 'pypi'
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
        with:
          packages-dir: ./dist
